parameters:
#    valk_wow.example.class: Valk\WowBundle\Example

services:
#    valk_wow.example:
#        class: %valk_wow.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
