valk_talent_calculator_with_class_with_build:
    pattern:  /talents/{class}/{build}
    defaults:
      _controller: ValkTalentCalculatorBundle:Default:index

valk_talent_calculator_with_class:
    pattern:  /talents/{class}/
    defaults:
      _controller: ValkTalentCalculatorBundle:Default:index
      build: ""

valk_talent_calculator:
    pattern:  /talents/
    defaults:
      _controller: ValkTalentCalculatorBundle:Default:index
      build: ""
      class: 1

