parameters:
#    valk_talent_calculator.example.class: Valk\Bundle\TalentCalculatorBundle\Example

services:
#    valk_talent_calculator.example:
#        class: %valk_talent_calculator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
