parameters:
#    valk_armory.example.class: Valk\ArmoryBundle\Example

services:
#    valk_armory.example:
#        class: %valk_armory.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
