valk_user:
    resource: "@ValkUserBundle/Resources/config/routing.yml"
    prefix:   /

valk_database:
    resource: "@ValkDatabaseBundle/Resources/config/routing.yml"
    prefix:   /

valk_armory:
    resource: "@ValkArmoryBundle/Resources/config/routing.yml"
    prefix:   /

valk_wow:
    resource: "@ValkWowBundle/Resources/config/routing.yml"
    prefix:   /

valk_main:
    resource: "@ValkMainBundle/Resources/config/routing.yml"
    prefix:   /

valk_account:
    resource: "@ValkAccountBundle/Resources/config/routing.yml"
    prefix:   /




