valk_main_homepage:
    pattern:  /
    defaults: { _controller: ValkMainBundle:Default:index }
valk_main_how_to_start:
    pattern:  /start/
    defaults: { _controller: ValkMainBundle:Default:howToStart }
