Valk\UserBundle\Entity\UserAccount:
    type: entity
    table: user_accounts
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        user:
            targetEntity: Valk\UserBundle\Entity\User
            inversedBy: user_accounts
            joinColumn:
                name: user_id
                referencedColumnName: id