Valk\UserBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        user_accounts:
            targetEntity: Valk\UserBundle\Entity\UserAccount
            mappedBy: user