Valk\UserBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        accounts_ids:
            type: simple_array
            nullable: true