parameters:
#    valk_account.example.class: Valk\AccountBundle\Example

services:
#    valk_account.example:
#        class: %valk_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
