valk_main_homepage:
    pattern:  /
    defaults: { _controller: ValkMainBundle:Pages:index }

valk_main_how_to_start:
    pattern:  /start/
    defaults: { _controller: ValkMainBundle:Pages:howToStart }

login:
    path:   /login
    defaults:  { _controller: ValkMainBundle:Pages:login }

login_check:
    path:   /login_check

logout:
    path:   /logout