parameters:
#    valk_main.example.class: Valk\Bundle\AccountBundle\Example


services:
#    valk_main.example:
#        class: %valk_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]