Valk\AccountBundle\Entity\Autobroadcast:
    type: entity
    table: autobroadcast
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        next:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
