parameters:
#    valk_database.example.class: Valk\DatabaseBundle\Example

services:
#    valk_database.example:
#        class: %valk_database.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
